### ISSUE TITLE
ND2 Incorrect getBitsPerPixel (Bit Depth)

### ISSUE THREAD

**Issue by MXGHarryLiu** [ome/bioformats#3490]
Hi bioformats developers, 

I notice a possible bug with **6.3.1**. For the sample files, please refer to QA **29008**. I am using MATLAB r2019b. 
To reproduce the issue, run the following scripts on the two files. 
```
reader = bfGetReader(path)
x = reader.getBitsPerPixel
```
Where `path` is the path of the file. 
The file 'E12-2p_1-1.nd2' will yield anticipated value: `x = 12`, whereas 'XMAS1_GFP.nd2' will be incorrect with `x = 16`. 
I also include a screenshot of NIS Viewer confirming that the latter recording is actually 12-bit. 
![image](https://user-images.githubusercontent.com/19699399/71844628-273bb300-308c-11ea-8b4b-54ad3cbec7f3.png)
Let me know if you need any information from me. 

Thanks,

**Comment by dgault** [comment]
Hi @MXGHarryLiu, thanks for the report and the provided sample file. When Bio-Formats reads the file it has 2 different metadata values stored within it:
```
uiBpcInMemory	16
uiBpcSignificant	12
```

Bio-Formats will read the Pixels as 16bit but both of these values will be able to be read using
```
bitsPerPixel = reader.getMetadataValue("uiBpcInMemory");
signifigantBits = reader.getMetadataValue("uiBpcSignificant");
```

**Comment by MXGHarryLiu** [comment]
Hi @dgault, 
Thanks for the prompt reply. I realized that the bit depth of the data and the actual data type to represent the data might be different. Does this mean that the file saves 12 bit info using 16 bit encoding? Besides using the `getMetadataValue` function, is there a way we can distinguish the two (like a counterpart get function), and please remind me that which bit depth is `getBitsPerPixel` referring to? What relevant to us might be the actual bit depth. 
Do you think I can use 
```
min(reader.getMetadataValue("uiBpcInMemory"), reader.getMetadataValue("uiBpcSignificant"))
``` 
to get what we want?

**Comment by dgault** [comment]
Yes essentially each Pixel will be stored in a 16bit data type even if the actual pixel data only has 12  bits of useful values. The `getBitsPerPixel` will refer to the number of bits which Bio-Formats is actually using to store each Pixel and so will refer to the data type rather than the number of significant bits.

The function you outlined would work fine to retrieve the value you want, or if you are only ever dealing with ND2 files of this nature then simply reading reader.getMetadataValue("uiBpcSignificant") would likely be enough.

**Comment by MXGHarryLiu** [comment]
Issue persists with **v6.6.1** with MATLAB r2021a. Adopted the workaround as suggested.
