### ISSUE TITLE
ZipException: invalid compression method

### ISSUE THREAD

**Issue by dominikl** [ome/bioformats#3843]
Zipped dicom image can't be extracted. But I could manually extract it and import the image.

[QA 31145](https://www.openmicroscopy.org/qa2/qa/feedback/31145/)
```
java.util.zip.ZipException: invalid compression method
	at java.util.zip.ZipInputStream.read(ZipInputStream.java:225)
	at java.util.zip.ZipInputStream.closeEntry(ZipInputStream.java:140)
	at java.util.zip.ZipInputStream.getNextEntry(ZipInputStream.java:118)
	at loci.common.ZipHandle.(ZipHandle.java:80)
...
```

**Comment by melissalinkert** [comment]
`unzip -v` on the supplied zip indicates that the legacy `implode` compression method was used. Java's zip implementation only supports the more common `stored` and `deflate` methods (https://docs.oracle.com/javase/8/docs/api/java/util/zip/ZipEntry.html#setMethod-int-).

Unzipping and then rezipping results in a file that uses the supported `deflate` compression method. The rezipped file can be read by `showinf`.

https://commons.apache.org/proper/commons-compress/ appears to have read-only support for `implode` compression. Fully supporting the original zip file would require switching `ZipHandle` from `ZipInputStream` to Commons Compress or similar.

I would be in favor of closing this as unsupported, especially since there are multiple work-arounds, but leaving open for now in case anyone else has strong feelings. If we want to actually support this feature, the issue could be moved to https://github.com/ome/ome-common-java since that's where the actual changes would happen.

**Comment by sbesson** [comment]
I second the proposal. BIo-Formats supports opening of zipped datasets. However unlike other scientific data, imaging requires random access rather than sequential access and built-in format compression schemes are usually a more efficient approach to reduce data sizes while keeping operations performant.

My 2p is there this is limited value in expanding the scope of the existing `ZipReader` and I would also vote for closing this as unsupported (and possibly improve the documentation the allowed compression methods).

**Comment by dgault** [comment]
Closing as unsupported
