### ISSUE TITLE
ND2 32-bit float

### ISSUE THREAD

**Issue by jburel** [ome/bioformats#3849]
Initial PR https://github.com/ome/bioformats/pull/3429

The problem seems to back
see https://forum.image.sc/t/32-bit-float-nd2s-are-assumed-to-be-integer-by-bio-formats/29040/9

**Comment by melissalinkert** [comment]
As far as I can see, there was no data associated with https://forum.image.sc/t/32-bit-float-nd2s-are-assumed-to-be-integer-by-bio-formats/29040/9, and the most recent activity on that thread suggested that an outdated version might have been in use. With no data and no updates in a year, closing since there isn't much we can do with this report. If there is a file that still has this problem, feel free to link it and re-open.
